name: fl_location_platform_interface
description: A common platform interface for the fl_location plugin.
publish_to: "none"

environment:
  flutter: ">=3.41.0"
  sdk: ">=3.11.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0
  vector_math: ^2.2.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.6.3
