name: fl_location
description: A plugin that can access the location services of each platform and collect device location data.
publish_to: "none"

environment:
  flutter: ">=3.41.0"
  sdk: ">=3.11.0"

dependencies:
  flutter:
    sdk: flutter
  fl_location_platform_interface:
    path: ../fl_location_platform_interface
  fl_location_web:
    path: ../fl_location_web

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.fl_location
        pluginClass: FlLocationPlugin
      ios:
        pluginClass: FlLocationPlugin
      web:
        default_package: fl_location_web
