name: fl_location_example
description: Demonstrates how to use the fl_location plugin.
publish_to: "none"

environment:
  flutter: ">=3.41.0"
  sdk: ">=3.11.0"

dependencies:
  flutter:
    sdk: flutter

  fl_location:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
